# Generated by Django 3.2.9 on 2022-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hoodie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Longsleeve',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'longsleeve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shirt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shortsleeve',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shortsleeve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sleeveless',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sleeveless',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sweat',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sweat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('personal_color', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sweater',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('faceId', models.AutoField(primary_key=True, serialize=False)),
                ('faceImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
