# Generated by Django 3.2.9 on 2021-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('collar_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hoodie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Longsleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'longsleeve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shirt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shortsleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shortsleeve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sleeveless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sleeveless',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sweat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sweat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('discount_price', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sweater',
                'managed': False,
            },
        ),
    ]
