# Generated by Django 3.2.9 on 2022-01-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
