# Generated by Django 3.2.9 on 2021-11-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Face',
        ),
    ]
