# Generated by Django 3.2.9 on 2021-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_auto_20211125_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='faceId',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
