# Generated by Django 3.2.9 on 2021-12-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0007_alter_faceimage_faceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='faceId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
