# Generated by Django 3.2.9 on 2021-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0008_alter_faceimage_faceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='faceImg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
