# Generated by Django 3.2.9 on 2021-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_alter_faceimage_faceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='faceImg',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
