# Generated by
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0010_alter_faceimage_faceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='faceImg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
